### ISSUE TITLE
Screenshots of whiteboard

### ISSUE THREAD

**Issue by FlorianJa** [FlorianJa/BeamLite-Unity#6]
Add a function to save the current whiteboard content

**Comment by FlorianJa** [comment]
Also load saved whiteboards

**Comment by Grosskopf** [comment]
Ok, i got a Branch with a functioning Savebutton, but it only is one Button, should i add numbers and make the Load button cycle through the saved whiteboards one by one on every click?

**Comment by FlorianJa** [comment]
for loading I imagine some kind of  a file open dialog with a overview of recent saved withboards. saving is fine for now. for loading i will create a new issue.

**Comment by FlorianJa** [comment]
fixed by https://github.com/FlorianJa/BeamLite-Unity/commit/87dd8fb05fc741ee5e9c87b922f33bc56b89fe16
